destination: "D:/Projects/wamp64/www/renewalscout-web/docs"

baseurl: "" # the subpath of your site, e.g. /blog
title: "RenewalScout" # the name of your site, e.g. ACME Corp.
url: "https://renewalscout.com" # the base hostname & protocol for your site, e.g. http://example.com